export const actionTypes = {
  GET_ALL_POSTS: "GET_ALL_POSTS",
  LIKE_POST: "LIKE_POST",
  DISLIKE_POST: "DISLIKE_POST",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_BOOKMARKS: "GET_ALL_BOOKMARKS",
  ADD_BOOKMARK: "ADD_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  CREATE_NEW_POST: "CREATE_NEW_POST",
  DELETE_POST: "DELETE_POST",
  EDIT_POST: "EDIT_POST",
  GET_SINGLE_USER: "GET_SINGLE_USER",
  GET_SINGLE_POST: "GET_SINGLE_POST",
  ADD_FOLLOWER: "ADD_FOLLOWER",
  ADD_FOLLOWING: "ADD_FOLLOWING",
  REMOVE_FOLLOWING: "REMOVE_FOLLOWING",
  REMOVE_FOLLOWER: "REMOVE_FOLLOWER",
  SEARCH_USER: "SEARCH_USER",
};

export const guestLoginDetails = {
  username: "dushyantcodes",
  password: "dushyantcodes123",
};
